language: node_js

node_js:
- "node"

cache:
  directories:
  - node_modules

env:
  global:
  # NPM_TOKEN
  - secure: "HYVIqU/pLzkxN8BVkYCP4GdFqoLkrmitcLBwCTXFvYp8yItn/8C1OqVUPIJGc7dLMU3NC0KIioR2Jry3TCEM/4i3GHrISHsRoE7PcdgGnQdAknZ7C58mJdW0tuVmnKAy4n+TiWVCiw115mmQLEtV8NP+oGGAl9BEDETDoaPxgp+2se/GR//MHyylm9lWlLgxJj0/5x8wmsbS7FOdhcNhNAZ0PoCRyPZXeT9tYoo7SB6aOxl+Cl4KoaqQqLQkFz1a10di3DiaMPYtQU2zgRpXAutK/+/ASvy8O/QIX33KyyW0Ajsyo6K/JDtNVqVk8v5+VSu5nss/BAV12TXgQdBW+n6wbWmsI71lUP58T4G9uk9AhvUGPSfanzSNVsZXusu1mvHErrvRNzpOHYAg8uA/4C2OlOGmuWiyqtKA02R7NJtc0eNqmEb64To8MtIYIHSx1lylSj/38vaIm1t/IzJ37G5KKEZt7/jf3LNrfBgCh9Y3lZ3zUjf6QsCsrqC9KTFYwVq4zUn3I9Sh3glQwZR54jiroZHmV7MHVfzZokd1cp3ArrUBhPuJTmiYIE+dEC+TH8SEHvyrscWXpEIZ+O6234EIyGUItizIAm3VqwMjwEnZxYxV8f4q7uCqQQIhlpuUN/5ZF8f/OL0045+/cHSwWxF9VBpAJFmagqKLOca5eaM="

install:
- npm install --progress=false

script:
- npm run test

after_success:
- npm run push-coverage-to-codecov

deploy:
- provider: script
  skip_cleanup: true
  script: $(npm bin)/prepack-publish
  on:
    tags: true
